import { Inter } from "next/font/google";
import "./globals.css";
import "../public/styles/apropos.css"
import "../public/styles/professionnel.css"
import "../public/styles/offre.css"
import "../public/styles/equipe.css"
import Head from "next/head";
import '../public/styles/demande.css'




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "INNOV-T Madagascar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" />
      </Head>
      <body className={inter.className}>{children}</body>
      
    </html>
  );
}
